name: lightgbm build workflow

on:
  push:
    branches:
      - build_v3_3_3

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # MacOS arm64 build job start
  job-macos-arm64-build-github-runner:
    runs-on: macos-14
    env:
      MACOSX_DEPLOYMENT_TARGET: "14"  # Set the minimum macOS version
      CIBW_BUILD: "cp311-*" # build on python 3.11
      CIBW_ARCHS_MACOS: "arm64" # build for arm64

    steps:
      - name: Output MacOS version
        run: |
          sw_vers

      - name: Output environment variables
        run: |
          env

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.18.1 wheel

      - name: Build MacOS wheel
        run: |
          cd python-package
          python -m cibuildwheel --output-dir dist
          ls -al dist
